"""Pre-implementation evidence: real two-question margin continuation failure.

The fixture is unedited live OCR, matched to the user's September 13 screenshot.
Expected order is manually annotated from that photo, not generated by layout.
The brace variant is a counterfactual experiment, never a recognition fixture.
"""
from collections import Counter
import json
from pathlib import Path
import unittest
from unittest.mock import patch

from core import layout
from tests.test_real_margin_layout import detection_key, member_key, row_ids


FIXTURE = Path(__file__).parent / "fixtures/writerX_two_question_margin_detections.json"
EXPECTED = [[i] for i in (
    0, 1, 3, 5, 7, 9, 12,  # Question 1, left
    2, 4, 6, 8, 10, 11,    # Question 1, right continuation
    13, 14, 16,             # Question 2, heading and left
    15, 17, 18, 19,         # Question 2, right continuation
)]


def records():
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def group(payload):
    return layout._group_detection_records(
        *[[d[k] for d in payload] for k in ("text", "score", "box")])


class ContinuationPlanningTests(unittest.TestCase):
    def test_real_two_question_continuations_belong_before_next_question(self):
        payload = records()
        rows, safe = group(payload)
        self.assertTrue(safe)
        self.assertEqual(row_ids(rows, payload), EXPECTED)

    def test_corrected_else_brace_variant_has_required_order(self):
        payload = records()
        self.assertEqual(payload[2]["text"], "{else {")
        payload[2]["text"] = "} else {"
        rows, safe = group(payload)
        self.assertTrue(safe)
        self.assertEqual(row_ids(rows, payload), EXPECTED)

    def test_all_twenty_detections_survive_verbatim(self):
        payload = records()
        rows, safe = group(payload)
        self.assertTrue(safe)
        self.assertEqual(len(payload), 20)
        self.assertEqual(Counter(member_key(m) for row in rows for m in row),
                         Counter(detection_key(d) for d in payload))

    def test_full_column_path_runs_association_before_returning(self):
        with (patch.object(layout, "_detect_banded_column",
                           wraps=layout._detect_banded_column) as band,
              patch.object(layout, "_reassemble_margin_candidates",
                           wraps=layout._reassemble_margin_candidates) as brace,
              patch.object(layout, "_associate_continuation",
                           wraps=layout._associate_continuation) as association):
            rows, safe = group(records())
        self.assertTrue(safe)
        self.assertEqual(len(rows), 20)
        band.assert_not_called()
        brace.assert_not_called()
        association.assert_called_once()


if __name__ == "__main__":
    unittest.main()
